name: commit
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "DEVIL"
          replace: "ARCANE"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Owner Updated'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Arcane120
          commit_user_email: officialarcane120@gmail.com
          commit_author: Arcane120 <officialarcane120@gmail.com>
