name: Fix
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "DEVIL"
          replace: "ARCANE"
      - name: Create Pull Request
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Auto Fixes'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: legendx22
          commit_user_email:legendxx0837@gmail.com
          commit_author: legendx22 <legendxx0837@gmail.com>
