name: Legendx22

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

                 
          find: "HellBot"

          replace: "LEGEND-BOT"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Akull on the beat'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: legendx22

          commit_user_email: legendxx0837@gmail.com
